# Generated by Django 4.1.3 on 2022-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
