# Generated by Django 4.1.3 on 2022-11-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='advertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdApp.advertise', verbose_name='Объявление'),
        ),
    ]
